### ISSUE TITLE
Some default constructors do not allocate all dynamic memory

### ISSUE THREAD

**Issue by jnalanko** [jnalanko/SubsetWT#3]
This leads to a crash at the destructor when it tries to free memory that has not been allocated

**Comment by ElenaBiagi** [comment]
SplitStructure, BitMagic and Predecessor?

**Comment by ElenaBiagi** [comment]
This issue is now solved for predecessor and BitMagic

**Comment by jnalanko** [comment]
SplitStructure fixed in cc53246.
