### ISSUE TITLE
Allow only alphabets of size 3 or 4 in base3/4 structures

### ISSUE THREAD

**Issue by jnalanko** [jnalanko/SubsetWT#5]
Throw an error or do not compile code that tries to use the base3/4 rank structures for other bases if the structure does not work correctly for those.

**Comment by ElenaBiagi** [comment]
Example of BitMagic<5> 

alphabet size = 5
terminate called after throwing an instance of 'std::invalid_argument'
  what():  BitMagic works only for alphabets of size 3 or 4.
./test.sh: line 15: 79665 Abort trap: 6           ./main

**Comment by jnalanko** [comment]
Added the same error to RRR generalization in e1a67c4.
